### ISSUE TITLE
Wondering how it works with CORS

### ISSUE THREAD

**Issue by despire1119** [sirrodgepodge/simple-iso-fetch#2]
if it has a option like ‘mode’？

**Comment by despire1119** [comment]
Have viewed the code and found the 'mode'.

**Comment by sirrodgepodge** [comment]
Hey there @despire1119, so the way this npm works is it tries to be smart about whether you need CORS enabled or not based on whether or not the route is a relative path (checks if it begins with '/') or is being made to the `baseURL` you have configured, if so the `mode` is set to `same-origin`, otherwise it is set to `cors`.

This default behavior can be overriden by explicitly providing a `mode` in your options object.  Make sense?
